## Mail Documenter Configuration
#

## mail ##
#
# Controls the configuration for the mail ferry.
#
mail:
  ## username ##
  #
  # The username for mail server login.
  #
  username: 

  ## password ##
  #
  # The user password for the mail server login.
  #
  password: 

  ## server ##
  #
  # The server address for the mail server, to fetch mails.
  #
  server: 

  ## folder ##
  #
  # The mail folder to fetch emails.
  #
  folder: INBOX

  ## filter_mode ##
  #
  # The filter mode enables/disables if the count, date and keyword based filters should be enabled or not.
  #
  filter_mode: OFF

  ## filter_type ##
  #
  # The filter type decides what type of filters needs to be applied.
  #
  filter_type: keyword

  ## readonly_mode ##
  #
  # The readonly mode enables/disables the movement of mail into the read section. 
  #
  readonly_mode: True

  ## count ##
  #
  # The total number of mails that should be fetched from the server.
  #
  count: 3

  ## start_date ##
  #
  # The start date from which the mails needs to be fetched. The mail start date should be greater than the mail end date. The date format for the start date is DDMMYYYY. If only start date is mentioned, mails received on that particular day alone will be fetched. if both start and end date is specified mails from that range will be fetched.
  #
  # Examples:
  # - The "March 1st of 2021" should be mentioned as 01032021
  #
  start_date: 09082021

  ## end_date ##
  #
  # The end date till which the mails needs to be fetched. The mail end date should be lesser than the mail start date. The date format for the end date is DDMMYYYY. If only end date is mentioned, mails received till that particular day will be fetched. if both start and end date is specified mails from that range will be fetched.
  #
  # Examples:
  # - The "March 1st of 2021" should be mentioned as 01032021
  #
  end_date: 09092021

  ## filter_keywords ##
  #
  # The keyword the mail ferry should use to filter the mails.
  #
  filter_keyword: welcome 

## document ##
#
# Controls the configuration for the document builder.
#
document:

  ## type ##
  #
  # The document type that should be used to write the email content.
  #
  type: pdf

  ## page_size ##
  #
  # The page size for the document, supports allowed document page size.
  #
  page_size: LETTER

  ## font_type ##
  #
  # The font type that should be used to write the email content.
  #
  font_type: Times-Roman

  ## font_size ##
  #
  # The font size that should be used to write the email content.
  #
  font_size: 12

  ## font_color ##
  #
  # The font color that should be used to write the email content.
  #
  font_color: black
